package com.rgprmexcel.confr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class consultaFr implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String abreviado;
	private java.lang.String ap;
	private java.lang.String codigoDelito;
	private java.lang.String dnp;
	private java.lang.String marca;
	private java.lang.String region;
	private java.lang.String respuestaPrincipal;
	private java.lang.String respuestaSecundaria;
	private java.lang.String scp;
	private java.lang.String sd;

	public consultaFr() {
	}

	public java.lang.String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(java.lang.String abreviado) {
		this.abreviado = abreviado;
	}

	public java.lang.String getAp() {
		return this.ap;
	}

	public void setAp(java.lang.String ap) {
		this.ap = ap;
	}

	public java.lang.String getCodigoDelito() {
		return this.codigoDelito;
	}

	public void setCodigoDelito(java.lang.String codigoDelito) {
		this.codigoDelito = codigoDelito;
	}

	public java.lang.String getDnp() {
		return this.dnp;
	}

	public void setDnp(java.lang.String dnp) {
		this.dnp = dnp;
	}

	public java.lang.String getMarca() {
		return this.marca;
	}

	public void setMarca(java.lang.String marca) {
		this.marca = marca;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.lang.String getRespuestaPrincipal() {
		return this.respuestaPrincipal;
	}

	public void setRespuestaPrincipal(java.lang.String respuestaPrincipal) {
		this.respuestaPrincipal = respuestaPrincipal;
	}

	public java.lang.String getRespuestaSecundaria() {
		return this.respuestaSecundaria;
	}

	public void setRespuestaSecundaria(java.lang.String respuestaSecundaria) {
		this.respuestaSecundaria = respuestaSecundaria;
	}

	public java.lang.String getScp() {
		return this.scp;
	}

	public void setScp(java.lang.String scp) {
		this.scp = scp;
	}

	public java.lang.String getSd() {
		return this.sd;
	}

	public void setSd(java.lang.String sd) {
		this.sd = sd;
	}

	public consultaFr(java.lang.String abreviado, java.lang.String ap,
			java.lang.String codigoDelito, java.lang.String dnp,
			java.lang.String marca, java.lang.String region,
			java.lang.String respuestaPrincipal,
			java.lang.String respuestaSecundaria, java.lang.String scp,
			java.lang.String sd) {
		this.abreviado = abreviado;
		this.ap = ap;
		this.codigoDelito = codigoDelito;
		this.dnp = dnp;
		this.marca = marca;
		this.region = region;
		this.respuestaPrincipal = respuestaPrincipal;
		this.respuestaSecundaria = respuestaSecundaria;
		this.scp = scp;
		this.sd = sd;
	}

}